# Imports
spring:
  config:
    import: classpath:env.properties
    profiles: ${PROFILE_ACTIVE}
  application:
    name: backend-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
server:
  server:
    port: ${PORT}
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui

